---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
rm(list = ls())

Link="https://github.com/meade68/DACSS_603D_Week04_HW1/raw/0e172a33a3842ccd5c0ac9c71e15097a3b1aa9a6/EUROPE_3035.gpkg"
library(sf)
st_layers(Link)
```

## Reading the layers:

```{r, message=FALSE}
DOT_DENSITY <- st_read(Link, layer = "DOT_DENSITY")
BASEMAP <- st_read(Link, layer = "BASEMAP")
CHOROPLETH <- st_read(Link, layer = "CHOROPLETH")
PROP_SYMBOL <- st_read(Link, layer = "PROP_SYMBOL")

```

## Checking CRS

```{r}
st_crs(PROP_SYMBOL)$epsg
```

# THE BASE

```{r}
library(ggplot2)
library(scales)

ggplot() + theme_light() +
  #call map
  geom_sf(data = BASEMAP) + 
  # adjust datum 
  coord_sf(datum = st_crs(BASEMAP)) + 
  # custom X and Y axes
  scale_x_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  scale_y_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  labs(x = "Easting", y = "Northing") #labels
```

# DDM - static

```{r}
plot1_a=ggplot() + theme_light() +
  #base
  geom_sf(data = BASEMAP,fill="white",color="grey80") +
  # layer
  geom_sf(data=DOT_DENSITY,
          alpha=0.1,#transparency
          shape=20,
          size=0.5,
          color="blue")+
  coord_sf(datum = st_crs(BASEMAP)) + 
  # custom X and Y axes
  scale_x_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  scale_y_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  labs(x = "Easting", y = "Northing") #labels

plot1_a
```

# DDM - interactive

```{r}
library(leaflet)
# needs geographic CRS


DOT_DENSITY<- st_cast(DOT_DENSITY,'POINT' )

ddm_4326 <- st_transform(DOT_DENSITY, crs = 4326)


leaflet() %>%
  addTiles() %>%  # base map
  addCircleMarkers(data = ddm_4326,
                   color="blue",
                   stroke=0,
                   radius = 0.01,
                   opacity = 0.1)
```

Almost the same:

```{r}
plot1_b=leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>%  # names in english
  addCircleMarkers(data = ddm_4326,
                   color="blue",
                   stroke=0,
                   radius = 0.01,
                   opacity = 0.1)
plot1_b
```

# PSM - static

```{r}


BASEMAP<-st_transform(BASEMAP, crs = 4326)

plot2_a=ggplot() + theme_light() +
  #base
  geom_sf(data = BASEMAP,fill="white",color="grey80") +
  # layer
  geom_sf(data=PROP_SYMBOL,
          shape=20,
          aes(size=size))+
  scale_size_area(
    name = "Mobiles per Person", # Name for the legend
    max_size = 20) +       # This defines the maximum *radius*
  guides(color="none") + 
  
  coord_sf(datum = st_crs(BASEMAP)) + 
  # custom X and Y axes
  scale_x_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  scale_y_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  labs(x = "Easting", y = "Northing") #labels

plot2_a  
```

# PSM - interactive

```{r}
# CRS for leaflet
psm_4326 <- st_transform(PROP_SYMBOL, crs = 4326)


plot2_b=leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>%  
  addCircleMarkers(data = psm_4326,
                   # fillColor = "red",
                   # stroke = T, #border
                   # color="red", #border color
                   # fillOpacity = 1,
                   label = ~Country,
                   radius = ~size)
plot2_b
```

# CHORO - static

```{r}
plot3_a=ggplot() + theme_light() +
  #base
  geom_sf(data=choro_4326,
          aes(fill=mobiles_pcapita_FJ5_cat))+
  coord_sf(datum = st_crs(BASEMAP)) +
  scale_fill_brewer(direction = 1,palette = 'RdBu') + 
  scale_x_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  scale_y_continuous(labels = label_number(scale = 1/1000, suffix = " km")) +
  labs(x = "Easting", y = "Northing",fill="Pop Density")
  
plot3_a
  
```

# CHORO - interactive

```{r}
choro_4326 <- st_transform(CHOROPLETH, crs = 4326)
#needed
choro_4326$mobiles_pcapita_FJ5_cat=ordered(choro_4326$mobiles_pcapita_FJ5_cat)
# First, create a color palette for your categorical variable
pal <- colorFactor(palette = "RdBu",
                   domain = choro_4326$mobiles_pcapita_FJ5_cat,
                   ordered = T,
                   reverse = F)

leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>% 
  addPolygons(
    data = choro_4326,
    fillColor = ~pal(mobiles_pcapita_FJ5_cat),
    fillOpacity = 0.7,
    color = "white",
    weight = 1,
    opacity = 1
    ) %>%
  addLegend(
    pal = pal,
    values = choro_4326$mobiles_pcapita_FJ5_cat,
    )
```

```{r}
# Calculate the center of Africa for the home button
europe_center <- st_bbox(choro_4326) %>% 
  as.vector() %>% 
  {c(mean(c(.[1], .[3])), mean(c(.[2], .[4])))}  # Calculate center coordinates


plot3_b=leaflet() %>%
  addProviderTiles(providers$CartoDB.Positron)  %>% 
addPolygons(
    data = choro_4326,
    fillColor = ~pal(mobiles_pcapita_FJ5_cat),
    fillOpacity = 0.7,
    color = "white",
    weight = 1,
    opacity = 1,
    label = lapply(
      paste("<strong>", choro_4326$Country, "</strong><br>",
            "Density: ", choro_4326$mobiles_pcapita_FJ5_cat),
      htmltools::HTML
    )
  ) %>%
  addLegend(
    pal = pal,
    values = choro_4326$mobiles_pcapita_FJ5_cat,
    opacity = 0.7,
    title = "Mobiles Density",
    position = "bottomright"
  )%>%
  addEasyButton(
    easyButton(
      icon = "fa-home", 
      title = "Reset to Central Europe View",
      onClick = JS(sprintf("function(btn, map){ map.setView([%f, %f], 3); }", 
                          europe_center[2], europe_center[1]))
    )
  )
plot3_b
```

```{r}
saveRDS(plot1_a,file = "plot1_a.rds")
saveRDS(plot1_b,file = "plot1_b.rds")
saveRDS(plot2_a,file = "plot2_a.rds")
saveRDS(plot2_b,file = "plot2_b.rds")
saveRDS(plot3_a,file = "plot3_a.rds")
saveRDS(plot3_b,file = "plot3_b.rds")
```
